server:
  port: 9081

spring:
  application:
    name: service-feign

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
          enabled: true
    lease:
          duration: 5
feign:
  hystrix:
    enabled: true