server:
  port: 8881

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: prod
      #uri: http://localhost:8888/   #read from config server directly