server:
  port: 9098

spring:
  application:
    name: service-ribbon

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
          enabled: true
    lease:
          duration: 5
